import os
import time
import logging
from typing import Optional
from pydantic import BaseModel, Field
from dotenv import load_dotenv

from app.agents.coordinator import MultiAgentCoordinator
from app.services.telemetry_service import telemetry_service

load_dotenv()

logger = logging.getLogger("chittakala.gemini_service")


class GeminiReflectionResponse(BaseModel):
    visual_observation: str = Field(
        ...,
        description="Warm, descriptive observation of the lines, dots, or geometric shapes drawn on paper."
    )
    encouragement: str = Field(
        ...,
        description="Affirming, non-judgmental sentence celebrating the user's creative pause."
    )
    next_step: str = Field(
        ...,
        description="Simple, non-pressured suggestion for their next drawing stroke or routine."
    )
    safety_status: str = Field(
        "safe",
        description="Safety evaluation flag ('safe' or 'flagged')"
    )
    needs_retake: bool = Field(
        False,
        description="True if image is pitch black, extremely blurry, or unreadable"
    )
    fallback_used: bool = Field(
        False,
        description="True if reflection was generated by local fallback handler"
    )


class GeminiReflectionService:
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.client = None

        if self.api_key:
            try:
                from google import genai
                self.client = genai.Client(api_key=self.api_key)
                logger.info("GeminiReflectionService initialized with live Gemini API Client & ADK Multi-Agent Coordinator.")
            except Exception as e:
                logger.warning(f"Failed to initialize google-genai Client: {e}. Fallback mode active.")

    def generate_fallback_reflection(self, art_form_title: str = "Indian Folk Art") -> GeminiReflectionResponse:
        """Safe local fallback reflection generator using ADK Multi-Agent Coordinator."""
        data = MultiAgentCoordinator.generate_fallback_synthesis(art_form_title)
        return GeminiReflectionResponse(**data)

    def reflect_on_drawing(
        self,
        image_bytes: bytes,
        session_id: str = "local_session",
        mime_type: str = "image/png",
        exercise_title: str = "Folk Art Exercise",
        art_form_title: str = "Indian Art"
    ) -> GeminiReflectionResponse:
        """
        Analyze user drawing bytes using ADK Multi-Agent Vision Architecture & Gemini 3.6 Flash.
        Logs latency and reliability events to BigQuery telemetry engine.
        """
        start_time = time.time()
        model_name = "gemini-3.6-flash"

        if not self.client or not self.api_key:
            logger.info("No Gemini API key configured. Serving fallback reflection.")
            fallback_res = self.generate_fallback_reflection(art_form_title)
            latency_ms = int((time.time() - start_time) * 1000)
            telemetry_service.log_ai_reliability_event(
                session_id=session_id,
                model_name=model_name,
                latency_ms=latency_ms,
                fallback_used=True,
                safety_status=fallback_res.safety_status,
                needs_retake=fallback_res.needs_retake
            )
            return fallback_res

        model_candidates = [
            "gemini-3.5-flash",
            "gemini-3.6-flash",
            "gemini-3.7-flash",
            "gemini-3.5-flash-lite",
            "gemini-flash-latest"
        ]
        last_error = None

        for model_name in model_candidates:
            try:
                from google import genai
                from google.genai import types

                system_instruction = MultiAgentCoordinator.get_orchestrated_system_instruction(
                    art_form_title=art_form_title,
                    exercise_title=exercise_title
                )

                prompt = (
                    f"Analyze this hand-drawn {art_form_title} sketch of '{exercise_title}'.\n"
                    f"Observe the hand-drawn lines, dots, curves, or geometric motifs on paper.\n"
                    f"Provide a warm, encouraging 3-part reflection adhering strictly to the JSON schema."
                )

                response = self.client.models.generate_content(
                    model=model_name,
                    contents=[
                        types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
                        prompt
                    ],
                    config=types.GenerateContentConfig(
                        system_instruction=system_instruction,
                        response_mime_type="application/json",
                        response_schema=GeminiReflectionResponse,
                        temperature=0.4,
                        max_output_tokens=2048,
                    )
                )

                latency_ms = int((time.time() - start_time) * 1000)

                if response and response.text:
                    text = response.text.strip()
                    if "```" in text:
                        lines = [line for line in text.split("\n") if not line.strip().startswith("```")]
                        text = "\n".join(lines).strip()
                    reflection = GeminiReflectionResponse.model_validate_json(text)
                    reflection.fallback_used = False

                    telemetry_service.log_ai_reliability_event(
                        session_id=session_id,
                        model_name=model_name,
                        latency_ms=latency_ms,
                        fallback_used=False,
                        safety_status=reflection.safety_status,
                        needs_retake=reflection.needs_retake
                    )
                    return reflection
            except Exception as e:
                logger.warning(f"Gemini API model {model_name} failed: {e}. Trying next model...")
                last_error = e

        logger.error(f"All Gemini API model candidates failed. Last error: {last_error}. Falling back safely to local synthesis.")
        latency_ms = int((time.time() - start_time) * 1000)
        fallback_res = self.generate_fallback_reflection(art_form_title)
        telemetry_service.log_ai_reliability_event(
            session_id=session_id,
            model_name="fallback_adk",
            latency_ms=latency_ms,
            fallback_used=True,
            safety_status="safe",
            needs_retake=False,
            error_message=str(last_error) if last_error else "Model candidates exhausted"
        )
        return fallback_res


# Global singleton instance
gemini_service = GeminiReflectionService()
